site_name: RoboHAT MM1
theme: readthedocs

repo_url: https://github.com/peterpanstechland/RoboHAT_DOC
edit_uri: edit/master/docs
#google_analytics: ['UA-99215530-2', 'github.io/donkey']
extra_css:
    - extra.css

pages:
    - Home: index.md
    - Hardware:
        - 'Pinout map': hardware/pinout.md
    - Firmwares:
        - 'Bootloader': firmwares/bootloader.md
        - 'Circuit Python': firmwares/circuitpython.md
        - 'Arduino': firmwares/arduino.md
        - 'Seesaw': firmwares/seesaw.md
        - 'Dronecode': firmwares/dronecode.md
    - User Guide:
        - 'Preperation': guide/preperation.md
        - 'Flash Firmware': guide/flash_firmware.md
        - 'API': guide/api.md
    - Parts:
        - 'About': parts/about.md
        - 'Actuators': parts/actuators.md
        - 'Controllers': parts/controllers.md
        - 'Stores': parts/stores.md
        - 'IMU': parts/imu.md
    # - Utilities:
    #     - 'donkey': utility/donkey.md
    - Example:
        - 'Donkey&reg; Car': example/donkeycar/donkeycar.md
        - '驴子车': example/donkeycar/donkeycar_cn.md

    - Supported Cars: supported_cars.md
    - Roll Your Own: roll_your_own.md
    - Contribute : contribute.md
    - Tests : tests.md
    - Releases : release.md
    - FAQ : faq.md
