site_name: RoboHAT MM1
theme: readthedocs

repo_url: https://github.com/robotics-masters/robohatmm1-docs
edit_uri: edit/master/docs
#google_analytics: ['UA-99215530-2', 'github.io/donkey']
extra_css:
    - extra.css

pages:
    - Home: index.md
    - Hardware:
        - 'Pinout map': hardware/pinout.md
    - Firmwares:
        - 'Bootloader': firmwares/bootloader.md
        - 'Circuit Python': firmwares/circuitpython.md
        - 'Arduino': firmwares/arduino.md
        - 'Seesaw': firmwares/seesaw.md
        - 'Dronecode': firmwares/dronecode.md
    - User Guide:
        - 'Preperation': guide/preperation.md
        - 'Circuit Python': guide/circuitpython.md
        - 'Circuit Python API': guide/Circuitpython API/Circuit_Python_API.md
        - 'Arduino': guide/arduino.md
        - 'Arduino API': guide/Arduino API/Arduino_API.md
    - Projects: 
        - 'RM EduCar' : projects/rmeducar.md

    - About: about.md
    - Contribute : contribute.md
    - FAQ : faq.md
